INSERT INTO disciplina (nome_disciplina, id_prof)
VALUES 
	('BANCOS DE DADOS I', 10),
	('BANCOS DE DADOS II', 9),
	('ENGENHARIA DE REQUISITOS', 8),
	('PROGRAMACÃO WEB', 7),
	('PROGRAMAÇÃO ORIENTADA A OBJETOS AVANCADA', 6),
	('REDES DE COMPUTADORES', 5),
	('PROGRAMAÇÃO PARA DISPOSITIVOS MÓVEIS', 4),
	('SEGURANÇA E AUDITORIA DE SISTEMAS', 3),
	('TESTES E QUALIDADE DE SOFTWARE', 2),
	('ARQUITETURA DE SOFTWARE', 1);
	